### ISSUE TITLE
リポジトリ管理について

### ISSUE THREAD

**Issue by watatuki** [TokaidoLUG/fireduckos#1]
cocon-setup-scripts の方式とrepo(例: agl-jetson)とどっちがいいですかね？

**Comment by ghost** [comment]
cocon-setup-scripts は Angstrom のものをfork して使っていますが、そちらは2年ほど動きがなく、かわりに repo に移行しているようです。
https://github.com/Angstrom-distribution/setup-scripts
https://github.com/Angstrom-distribution/angstrom-manifest
なので、これから作るには repo の方がよいかなと思っています。

**Comment by watatuki** [comment]
repoで作ってみました。
アーキ・ボードの切り分けはAGLのセットアップスクリプトを流用しています。
